### ISSUE TITLE
Fresh generated app cannot run

### ISSUE THREAD

**Issue by gogames** [jermspeaks/generator-react-redux#10]
`npm start` after generating app, error occurs:

```
> dllm@0.0.0 start /Users/d/workspace/js/dllm
> babel-node tools/run start

/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/file/plugin-manager.js:159
      throw new ReferenceError(messages.get("pluginKeyCollision", key));
      ^

ReferenceError: The plugin "react.displayName" collides with another of the same name
    at PluginManager.validate (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/file/plugin-manager.js:159:13)
    at PluginManager.add (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transformFileSync (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/api/node.js:137:37)
    at compile (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/d/workspace/js/dllm/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! dllm@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dllm@0.0.0 start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dllm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls dllm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/d/workspace/js/dllm/npm-debug.log
```

**Comment by gogames** [comment]
A patch like https://github.com/banderson/generator-redux/pull/40 should work
